// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0r7r-dAEZsc8LbmXbHMSBDywIoEnzjK8',
    appId: '1:140224742269:web:6dd8dad1b2a71de3538214',
    messagingSenderId: '140224742269',
    projectId: 'btl-chat-app-de753',
    authDomain: 'btl-chat-app-de753.firebaseapp.com',
    storageBucket: 'btl-chat-app-de753.appspot.com',
    measurementId: 'G-2X1WVZFY9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5z0ThJZgH-w6dsm-_CrQMHDuvW1IZaQ',
    appId: '1:140224742269:android:2075da611a835441538214',
    messagingSenderId: '140224742269',
    projectId: 'btl-chat-app-de753',
    storageBucket: 'btl-chat-app-de753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuYBMYTJuBvdi8F8deMCpKlcEtOnIcwA0',
    appId: '1:140224742269:ios:18f18a38b23ab0f6538214',
    messagingSenderId: '140224742269',
    projectId: 'btl-chat-app-de753',
    storageBucket: 'btl-chat-app-de753.appspot.com',
    iosBundleId: 'com.example.btlFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuYBMYTJuBvdi8F8deMCpKlcEtOnIcwA0',
    appId: '1:140224742269:ios:18f18a38b23ab0f6538214',
    messagingSenderId: '140224742269',
    projectId: 'btl-chat-app-de753',
    storageBucket: 'btl-chat-app-de753.appspot.com',
    iosBundleId: 'com.example.btlFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0r7r-dAEZsc8LbmXbHMSBDywIoEnzjK8',
    appId: '1:140224742269:web:9eb3d9b07b1655dd538214',
    messagingSenderId: '140224742269',
    projectId: 'btl-chat-app-de753',
    authDomain: 'btl-chat-app-de753.firebaseapp.com',
    storageBucket: 'btl-chat-app-de753.appspot.com',
    measurementId: 'G-473H9CHH13',
  );
}
